apiVersion: v1
kind: Service
metadata:
  name: mysql-service  # This matches what backend is trying to connect to
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306